/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  serial,
  numeric,
  jsonb,
  boolean,
  timestamp,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
import { geometryColumn } from "@payloadcms/db-postgres";
export const enum_games_language_dependence = pgEnum(
  "enum_games_language_dependence",
  ["0", "1", "2", "3", "4"]
);
export const enum_users_roles = pgEnum("enum_users_roles", ["admin", "user"]);

export const accessories_alternate_names = pgTable(
  "accessories_alternate_names",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    name: varchar("name"),
  },
  (columns) => ({
    _orderIdx: index("accessories_alternate_names_order_idx").on(
      columns._order
    ),
    _parentIDIdx: index("accessories_alternate_names_parent_id_idx").on(
      columns._parentID
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [accessories.id],
      name: "accessories_alternate_names_parent_id_fk",
    }).onDelete("cascade"),
  })
);

export const accessories = pgTable(
  "accessories",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    description: jsonb("description"),
    "affiliate link": varchar("affiliate_link"),
    yearPublished: numeric("year_published"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    accessories_bgg_id_idx: uniqueIndex("accessories_bgg_id_idx").on(
      columns.bggId
    ),
    accessories_updated_at_idx: index("accessories_updated_at_idx").on(
      columns.updatedAt
    ),
    accessories_created_at_idx: index("accessories_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const accessories_rels = pgTable(
  "accessories_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
    publishersID: integer("publishers_id"),
  },
  (columns) => ({
    order: index("accessories_rels_order_idx").on(columns.order),
    parentIdx: index("accessories_rels_parent_idx").on(columns.parent),
    pathIdx: index("accessories_rels_path_idx").on(columns.path),
    accessories_rels_media_id_idx: index("accessories_rels_media_id_idx").on(
      columns.mediaID
    ),
    accessories_rels_publishers_id_idx: index(
      "accessories_rels_publishers_id_idx"
    ).on(columns.publishersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [accessories.id],
      name: "accessories_rels_parent_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "accessories_rels_media_fk",
    }).onDelete("cascade"),
    publishersIdFk: foreignKey({
      columns: [columns["publishersID"]],
      foreignColumns: [publishers.id],
      name: "accessories_rels_publishers_fk",
    }).onDelete("cascade"),
  })
);

export const artists = pgTable(
  "artists",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    description: jsonb("description"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    artists_updated_at_idx: index("artists_updated_at_idx").on(
      columns.updatedAt
    ),
    artists_created_at_idx: index("artists_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const categories = pgTable(
  "categories",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    categories_updated_at_idx: index("categories_updated_at_idx").on(
      columns.updatedAt
    ),
    categories_created_at_idx: index("categories_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const designers = pgTable(
  "designers",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    description: jsonb("description"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    designers_updated_at_idx: index("designers_updated_at_idx").on(
      columns.updatedAt
    ),
    designers_created_at_idx: index("designers_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const gamenights = pgTable(
  "gamenights",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    description: jsonb("description"),
    date: timestamp("date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    location: geometryColumn("location"),
    recurring: boolean("recurring").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    gamenights_updated_at_idx: index("gamenights_updated_at_idx").on(
      columns.updatedAt
    ),
    gamenights_created_at_idx: index("gamenights_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const gamenights_rels = pgTable(
  "gamenights_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    gamesID: integer("games_id"),
  },
  (columns) => ({
    order: index("gamenights_rels_order_idx").on(columns.order),
    parentIdx: index("gamenights_rels_parent_idx").on(columns.parent),
    pathIdx: index("gamenights_rels_path_idx").on(columns.path),
    gamenights_rels_users_id_idx: index("gamenights_rels_users_id_idx").on(
      columns.usersID
    ),
    gamenights_rels_games_id_idx: index("gamenights_rels_games_id_idx").on(
      columns.gamesID
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [gamenights.id],
      name: "gamenights_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "gamenights_rels_users_fk",
    }).onDelete("cascade"),
    gamesIdFk: foreignKey({
      columns: [columns["gamesID"]],
      foreignColumns: [games.id],
      name: "gamenights_rels_games_fk",
    }).onDelete("cascade"),
  })
);

export const games_suggested_player_count = pgTable(
  "games_suggested_player_count",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    playerCount: numeric("player_count"),
    bestCount: numeric("best_count"),
    recommendedCount: numeric("recommended_count"),
    notRecommendedCount: numeric("not_recommended_count"),
  },
  (columns) => ({
    _orderIdx: index("games_suggested_player_count_order_idx").on(
      columns._order
    ),
    _parentIDIdx: index("games_suggested_player_count_parent_id_idx").on(
      columns._parentID
    ),
    _parentIDFk: foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [games.id],
      name: "games_suggested_player_count_parent_id_fk",
    }).onDelete("cascade"),
  })
);

export const games = pgTable(
  "games",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    originalName: varchar("original_name"),
    description: jsonb("description"),
    "affiliate link": varchar("affiliate_link"),
    yearPublished: numeric("year_published"),
    minPlayers: numeric("min_players"),
    maxPlayers: numeric("max_players"),
    playingTime: numeric("playing_time"),
    minPlaytime: numeric("min_playtime"),
    maxPlaytime: numeric("max_playtime"),
    minAge: numeric("min_age"),
    complexity: numeric("complexity"),
    userRating: numeric("user_rating"),
    userRatedCount: numeric("user_rated_count"),
    "official link": varchar("official_link"),
    bggRank: numeric("bgg_rank"),
    baseGame: integer("base_game_id").references((): AnyPgColumn => games.id, {
      onDelete: "set null",
    }),
    languageDependence: enum_games_language_dependence("language_dependence"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    games_bgg_id_idx: uniqueIndex("games_bgg_id_idx").on(columns.bggId),
    games_base_game_idx: index("games_base_game_idx").on(columns.baseGame),
    games_updated_at_idx: index("games_updated_at_idx").on(columns.updatedAt),
    games_created_at_idx: index("games_created_at_idx").on(columns.createdAt),
  })
);

export const games_rels = pgTable(
  "games_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
    typesID: integer("types_id"),
    categoriesID: integer("categories_id"),
    mechanicsID: integer("mechanics_id"),
    designersID: integer("designers_id"),
    publishersID: integer("publishers_id"),
    artistsID: integer("artists_id"),
    gamesID: integer("games_id"),
    accessoriesID: integer("accessories_id"),
  },
  (columns) => ({
    order: index("games_rels_order_idx").on(columns.order),
    parentIdx: index("games_rels_parent_idx").on(columns.parent),
    pathIdx: index("games_rels_path_idx").on(columns.path),
    games_rels_media_id_idx: index("games_rels_media_id_idx").on(
      columns.mediaID
    ),
    games_rels_types_id_idx: index("games_rels_types_id_idx").on(
      columns.typesID
    ),
    games_rels_categories_id_idx: index("games_rels_categories_id_idx").on(
      columns.categoriesID
    ),
    games_rels_mechanics_id_idx: index("games_rels_mechanics_id_idx").on(
      columns.mechanicsID
    ),
    games_rels_designers_id_idx: index("games_rels_designers_id_idx").on(
      columns.designersID
    ),
    games_rels_publishers_id_idx: index("games_rels_publishers_id_idx").on(
      columns.publishersID
    ),
    games_rels_artists_id_idx: index("games_rels_artists_id_idx").on(
      columns.artistsID
    ),
    games_rels_games_id_idx: index("games_rels_games_id_idx").on(
      columns.gamesID
    ),
    games_rels_accessories_id_idx: index("games_rels_accessories_id_idx").on(
      columns.accessoriesID
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [games.id],
      name: "games_rels_parent_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "games_rels_media_fk",
    }).onDelete("cascade"),
    typesIdFk: foreignKey({
      columns: [columns["typesID"]],
      foreignColumns: [types.id],
      name: "games_rels_types_fk",
    }).onDelete("cascade"),
    categoriesIdFk: foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "games_rels_categories_fk",
    }).onDelete("cascade"),
    mechanicsIdFk: foreignKey({
      columns: [columns["mechanicsID"]],
      foreignColumns: [mechanics.id],
      name: "games_rels_mechanics_fk",
    }).onDelete("cascade"),
    designersIdFk: foreignKey({
      columns: [columns["designersID"]],
      foreignColumns: [designers.id],
      name: "games_rels_designers_fk",
    }).onDelete("cascade"),
    publishersIdFk: foreignKey({
      columns: [columns["publishersID"]],
      foreignColumns: [publishers.id],
      name: "games_rels_publishers_fk",
    }).onDelete("cascade"),
    artistsIdFk: foreignKey({
      columns: [columns["artistsID"]],
      foreignColumns: [artists.id],
      name: "games_rels_artists_fk",
    }).onDelete("cascade"),
    gamesIdFk: foreignKey({
      columns: [columns["gamesID"]],
      foreignColumns: [games.id],
      name: "games_rels_games_fk",
    }).onDelete("cascade"),
    accessoriesIdFk: foreignKey({
      columns: [columns["accessoriesID"]],
      foreignColumns: [accessories.id],
      name: "games_rels_accessories_fk",
    }).onDelete("cascade"),
  })
);

export const libraries = pgTable(
  "libraries",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    description: jsonb("description"),
    createdBy: integer("created_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    libraries_created_by_idx: index("libraries_created_by_idx").on(
      columns.createdBy
    ),
    libraries_updated_at_idx: index("libraries_updated_at_idx").on(
      columns.updatedAt
    ),
    libraries_created_at_idx: index("libraries_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const libraries_rels = pgTable(
  "libraries_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    gamesID: integer("games_id"),
  },
  (columns) => ({
    order: index("libraries_rels_order_idx").on(columns.order),
    parentIdx: index("libraries_rels_parent_idx").on(columns.parent),
    pathIdx: index("libraries_rels_path_idx").on(columns.path),
    libraries_rels_games_id_idx: index("libraries_rels_games_id_idx").on(
      columns.gamesID
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [libraries.id],
      name: "libraries_rels_parent_fk",
    }).onDelete("cascade"),
    gamesIdFk: foreignKey({
      columns: [columns["gamesID"]],
      foreignColumns: [games.id],
      name: "libraries_rels_games_fk",
    }).onDelete("cascade"),
  })
);

export const mechanics = pgTable(
  "mechanics",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    mechanics_updated_at_idx: index("mechanics_updated_at_idx").on(
      columns.updatedAt
    ),
    mechanics_created_at_idx: index("mechanics_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    prefix: varchar("prefix").default("games"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width"),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height"),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize"),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width"),
    sizes_card_height: numeric("sizes_card_height"),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize"),
    sizes_card_filename: varchar("sizes_card_filename"),
  },
  (columns) => ({
    media_updated_at_idx: index("media_updated_at_idx").on(columns.updatedAt),
    media_created_at_idx: index("media_created_at_idx").on(columns.createdAt),
    media_filename_idx: uniqueIndex("media_filename_idx").on(columns.filename),
    media_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      "media_sizes_thumbnail_sizes_thumbnail_filename_idx"
    ).on(columns.sizes_thumbnail_filename),
    media_sizes_card_sizes_card_filename_idx: index(
      "media_sizes_card_sizes_card_filename_idx"
    ).on(columns.sizes_card_filename),
  })
);

export const notes = pgTable(
  "notes",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    notes: jsonb("notes"),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    notes_user_idx: index("notes_user_idx").on(columns.user),
    notes_updated_at_idx: index("notes_updated_at_idx").on(columns.updatedAt),
    notes_created_at_idx: index("notes_created_at_idx").on(columns.createdAt),
  })
);

export const publishers = pgTable(
  "publishers",
  {
    id: serial("id").primaryKey(),
    bggId: numeric("bgg_id"),
    name: varchar("name"),
    description: jsonb("description"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    publishers_updated_at_idx: index("publishers_updated_at_idx").on(
      columns.updatedAt
    ),
    publishers_created_at_idx: index("publishers_created_at_idx").on(
      columns.createdAt
    ),
  })
);

export const publishers_rels = pgTable(
  "publishers_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    mediaID: integer("media_id"),
  },
  (columns) => ({
    order: index("publishers_rels_order_idx").on(columns.order),
    parentIdx: index("publishers_rels_parent_idx").on(columns.parent),
    pathIdx: index("publishers_rels_path_idx").on(columns.path),
    publishers_rels_media_id_idx: index("publishers_rels_media_id_idx").on(
      columns.mediaID
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [publishers.id],
      name: "publishers_rels_parent_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "publishers_rels_media_fk",
    }).onDelete("cascade"),
  })
);

export const types = pgTable(
  "types",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    processing: boolean("processing").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    types_updated_at_idx: index("types_updated_at_idx").on(columns.updatedAt),
    types_created_at_idx: index("types_created_at_idx").on(columns.createdAt),
  })
);

export const usermedia = pgTable(
  "usermedia",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    gameId: varchar("game_id"),
    gameName: varchar("game_name"),
    prefix: varchar("prefix").default("usermedia"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize"),
    width: numeric("width"),
    height: numeric("height"),
    focalX: numeric("focal_x"),
    focalY: numeric("focal_y"),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width"),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height"),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize"),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width"),
    sizes_card_height: numeric("sizes_card_height"),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize"),
    sizes_card_filename: varchar("sizes_card_filename"),
  },
  (columns) => ({
    usermedia_updated_at_idx: index("usermedia_updated_at_idx").on(
      columns.updatedAt
    ),
    usermedia_created_at_idx: index("usermedia_created_at_idx").on(
      columns.createdAt
    ),
    usermedia_filename_idx: uniqueIndex("usermedia_filename_idx").on(
      columns.filename
    ),
    usermedia_sizes_thumbnail_sizes_thumbnail_filename_idx: index(
      "usermedia_sizes_thumbnail_sizes_thumbnail_filename_idx"
    ).on(columns.sizes_thumbnail_filename),
    usermedia_sizes_card_sizes_card_filename_idx: index(
      "usermedia_sizes_card_sizes_card_filename_idx"
    ).on(columns.sizes_card_filename),
  })
);

export const users_roles = pgTable(
  "users_roles",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_users_roles("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => ({
    orderIdx: index("users_roles_order_idx").on(columns.order),
    parentIdx: index("users_roles_parent_idx").on(columns.parent),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_roles_parent_fk",
    }).onDelete("cascade"),
  })
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    username: varchar("username").notNull(),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    phone: numeric("phone"),
    avatar: integer("avatar_id").references(() => usermedia.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    _verified: boolean("_verified"),
    _verificationToken: varchar("_verificationtoken"),
    loginAttempts: numeric("login_attempts").default("0"),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => ({
    users_username_idx: uniqueIndex("users_username_idx").on(columns.username),
    users_avatar_idx: uniqueIndex("users_avatar_idx").on(columns.avatar),
    users_updated_at_idx: index("users_updated_at_idx").on(columns.updatedAt),
    users_created_at_idx: index("users_created_at_idx").on(columns.createdAt),
    users_email_idx: uniqueIndex("users_email_idx").on(columns.email),
  })
);

export const users_rels = pgTable(
  "users_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    librariesID: integer("libraries_id"),
    gamenightsID: integer("gamenights_id"),
    usersID: integer("users_id"),
    notesID: integer("notes_id"),
  },
  (columns) => ({
    order: index("users_rels_order_idx").on(columns.order),
    parentIdx: index("users_rels_parent_idx").on(columns.parent),
    pathIdx: index("users_rels_path_idx").on(columns.path),
    users_rels_libraries_id_idx: index("users_rels_libraries_id_idx").on(
      columns.librariesID
    ),
    users_rels_gamenights_id_idx: index("users_rels_gamenights_id_idx").on(
      columns.gamenightsID
    ),
    users_rels_users_id_idx: index("users_rels_users_id_idx").on(
      columns.usersID
    ),
    users_rels_notes_id_idx: index("users_rels_notes_id_idx").on(
      columns.notesID
    ),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_rels_parent_fk",
    }).onDelete("cascade"),
    librariesIdFk: foreignKey({
      columns: [columns["librariesID"]],
      foreignColumns: [libraries.id],
      name: "users_rels_libraries_fk",
    }).onDelete("cascade"),
    gamenightsIdFk: foreignKey({
      columns: [columns["gamenightsID"]],
      foreignColumns: [gamenights.id],
      name: "users_rels_gamenights_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "users_rels_users_fk",
    }).onDelete("cascade"),
    notesIdFk: foreignKey({
      columns: [columns["notesID"]],
      foreignColumns: [notes.id],
      name: "users_rels_notes_fk",
    }).onDelete("cascade"),
  })
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index(
      "payload_locked_documents_global_slug_idx"
    ).on(columns.globalSlug),
    payload_locked_documents_updated_at_idx: index(
      "payload_locked_documents_updated_at_idx"
    ).on(columns.updatedAt),
    payload_locked_documents_created_at_idx: index(
      "payload_locked_documents_created_at_idx"
    ).on(columns.createdAt),
  })
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    accessoriesID: integer("accessories_id"),
    artistsID: integer("artists_id"),
    categoriesID: integer("categories_id"),
    designersID: integer("designers_id"),
    gamenightsID: integer("gamenights_id"),
    gamesID: integer("games_id"),
    librariesID: integer("libraries_id"),
    mechanicsID: integer("mechanics_id"),
    mediaID: integer("media_id"),
    notesID: integer("notes_id"),
    publishersID: integer("publishers_id"),
    typesID: integer("types_id"),
    usermediaID: integer("usermedia_id"),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_locked_documents_rels_order_idx").on(columns.order),
    parentIdx: index("payload_locked_documents_rels_parent_idx").on(
      columns.parent
    ),
    pathIdx: index("payload_locked_documents_rels_path_idx").on(columns.path),
    payload_locked_documents_rels_accessories_id_idx: index(
      "payload_locked_documents_rels_accessories_id_idx"
    ).on(columns.accessoriesID),
    payload_locked_documents_rels_artists_id_idx: index(
      "payload_locked_documents_rels_artists_id_idx"
    ).on(columns.artistsID),
    payload_locked_documents_rels_categories_id_idx: index(
      "payload_locked_documents_rels_categories_id_idx"
    ).on(columns.categoriesID),
    payload_locked_documents_rels_designers_id_idx: index(
      "payload_locked_documents_rels_designers_id_idx"
    ).on(columns.designersID),
    payload_locked_documents_rels_gamenights_id_idx: index(
      "payload_locked_documents_rels_gamenights_id_idx"
    ).on(columns.gamenightsID),
    payload_locked_documents_rels_games_id_idx: index(
      "payload_locked_documents_rels_games_id_idx"
    ).on(columns.gamesID),
    payload_locked_documents_rels_libraries_id_idx: index(
      "payload_locked_documents_rels_libraries_id_idx"
    ).on(columns.librariesID),
    payload_locked_documents_rels_mechanics_id_idx: index(
      "payload_locked_documents_rels_mechanics_id_idx"
    ).on(columns.mechanicsID),
    payload_locked_documents_rels_media_id_idx: index(
      "payload_locked_documents_rels_media_id_idx"
    ).on(columns.mediaID),
    payload_locked_documents_rels_notes_id_idx: index(
      "payload_locked_documents_rels_notes_id_idx"
    ).on(columns.notesID),
    payload_locked_documents_rels_publishers_id_idx: index(
      "payload_locked_documents_rels_publishers_id_idx"
    ).on(columns.publishersID),
    payload_locked_documents_rels_types_id_idx: index(
      "payload_locked_documents_rels_types_id_idx"
    ).on(columns.typesID),
    payload_locked_documents_rels_usermedia_id_idx: index(
      "payload_locked_documents_rels_usermedia_id_idx"
    ).on(columns.usermediaID),
    payload_locked_documents_rels_users_id_idx: index(
      "payload_locked_documents_rels_users_id_idx"
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    accessoriesIdFk: foreignKey({
      columns: [columns["accessoriesID"]],
      foreignColumns: [accessories.id],
      name: "payload_locked_documents_rels_accessories_fk",
    }).onDelete("cascade"),
    artistsIdFk: foreignKey({
      columns: [columns["artistsID"]],
      foreignColumns: [artists.id],
      name: "payload_locked_documents_rels_artists_fk",
    }).onDelete("cascade"),
    categoriesIdFk: foreignKey({
      columns: [columns["categoriesID"]],
      foreignColumns: [categories.id],
      name: "payload_locked_documents_rels_categories_fk",
    }).onDelete("cascade"),
    designersIdFk: foreignKey({
      columns: [columns["designersID"]],
      foreignColumns: [designers.id],
      name: "payload_locked_documents_rels_designers_fk",
    }).onDelete("cascade"),
    gamenightsIdFk: foreignKey({
      columns: [columns["gamenightsID"]],
      foreignColumns: [gamenights.id],
      name: "payload_locked_documents_rels_gamenights_fk",
    }).onDelete("cascade"),
    gamesIdFk: foreignKey({
      columns: [columns["gamesID"]],
      foreignColumns: [games.id],
      name: "payload_locked_documents_rels_games_fk",
    }).onDelete("cascade"),
    librariesIdFk: foreignKey({
      columns: [columns["librariesID"]],
      foreignColumns: [libraries.id],
      name: "payload_locked_documents_rels_libraries_fk",
    }).onDelete("cascade"),
    mechanicsIdFk: foreignKey({
      columns: [columns["mechanicsID"]],
      foreignColumns: [mechanics.id],
      name: "payload_locked_documents_rels_mechanics_fk",
    }).onDelete("cascade"),
    mediaIdFk: foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    notesIdFk: foreignKey({
      columns: [columns["notesID"]],
      foreignColumns: [notes.id],
      name: "payload_locked_documents_rels_notes_fk",
    }).onDelete("cascade"),
    publishersIdFk: foreignKey({
      columns: [columns["publishersID"]],
      foreignColumns: [publishers.id],
      name: "payload_locked_documents_rels_publishers_fk",
    }).onDelete("cascade"),
    typesIdFk: foreignKey({
      columns: [columns["typesID"]],
      foreignColumns: [types.id],
      name: "payload_locked_documents_rels_types_fk",
    }).onDelete("cascade"),
    usermediaIdFk: foreignKey({
      columns: [columns["usermediaID"]],
      foreignColumns: [usermedia.id],
      name: "payload_locked_documents_rels_usermedia_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  })
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index("payload_preferences_key_idx").on(
      columns.key
    ),
    payload_preferences_updated_at_idx: index(
      "payload_preferences_updated_at_idx"
    ).on(columns.updatedAt),
    payload_preferences_created_at_idx: index(
      "payload_preferences_created_at_idx"
    ).on(columns.createdAt),
  })
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => ({
    order: index("payload_preferences_rels_order_idx").on(columns.order),
    parentIdx: index("payload_preferences_rels_parent_idx").on(columns.parent),
    pathIdx: index("payload_preferences_rels_path_idx").on(columns.path),
    payload_preferences_rels_users_id_idx: index(
      "payload_preferences_rels_users_id_idx"
    ).on(columns.usersID),
    parentFk: foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    usersIdFk: foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  })
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index(
      "payload_migrations_updated_at_idx"
    ).on(columns.updatedAt),
    payload_migrations_created_at_idx: index(
      "payload_migrations_created_at_idx"
    ).on(columns.createdAt),
  })
);

export const relations_accessories_alternate_names = relations(
  accessories_alternate_names,
  ({ one }) => ({
    _parentID: one(accessories, {
      fields: [accessories_alternate_names._parentID],
      references: [accessories.id],
      relationName: "alternateNames",
    }),
  })
);
export const relations_accessories_rels = relations(
  accessories_rels,
  ({ one }) => ({
    parent: one(accessories, {
      fields: [accessories_rels.parent],
      references: [accessories.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [accessories_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    publishersID: one(publishers, {
      fields: [accessories_rels.publishersID],
      references: [publishers.id],
      relationName: "publishers",
    }),
  })
);
export const relations_accessories = relations(accessories, ({ many }) => ({
  alternateNames: many(accessories_alternate_names, {
    relationName: "alternateNames",
  }),
  _rels: many(accessories_rels, {
    relationName: "_rels",
  }),
}));
export const relations_artists = relations(artists, () => ({}));
export const relations_categories = relations(categories, () => ({}));
export const relations_designers = relations(designers, () => ({}));
export const relations_gamenights_rels = relations(
  gamenights_rels,
  ({ one }) => ({
    parent: one(gamenights, {
      fields: [gamenights_rels.parent],
      references: [gamenights.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [gamenights_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    gamesID: one(games, {
      fields: [gamenights_rels.gamesID],
      references: [games.id],
      relationName: "games",
    }),
  })
);
export const relations_gamenights = relations(gamenights, ({ many }) => ({
  _rels: many(gamenights_rels, {
    relationName: "_rels",
  }),
}));
export const relations_games_suggested_player_count = relations(
  games_suggested_player_count,
  ({ one }) => ({
    _parentID: one(games, {
      fields: [games_suggested_player_count._parentID],
      references: [games.id],
      relationName: "suggestedPlayerCount",
    }),
  })
);
export const relations_games_rels = relations(games_rels, ({ one }) => ({
  parent: one(games, {
    fields: [games_rels.parent],
    references: [games.id],
    relationName: "_rels",
  }),
  mediaID: one(media, {
    fields: [games_rels.mediaID],
    references: [media.id],
    relationName: "media",
  }),
  typesID: one(types, {
    fields: [games_rels.typesID],
    references: [types.id],
    relationName: "types",
  }),
  categoriesID: one(categories, {
    fields: [games_rels.categoriesID],
    references: [categories.id],
    relationName: "categories",
  }),
  mechanicsID: one(mechanics, {
    fields: [games_rels.mechanicsID],
    references: [mechanics.id],
    relationName: "mechanics",
  }),
  designersID: one(designers, {
    fields: [games_rels.designersID],
    references: [designers.id],
    relationName: "designers",
  }),
  publishersID: one(publishers, {
    fields: [games_rels.publishersID],
    references: [publishers.id],
    relationName: "publishers",
  }),
  artistsID: one(artists, {
    fields: [games_rels.artistsID],
    references: [artists.id],
    relationName: "artists",
  }),
  gamesID: one(games, {
    fields: [games_rels.gamesID],
    references: [games.id],
    relationName: "games",
  }),
  accessoriesID: one(accessories, {
    fields: [games_rels.accessoriesID],
    references: [accessories.id],
    relationName: "accessories",
  }),
}));
export const relations_games = relations(games, ({ one, many }) => ({
  baseGame: one(games, {
    fields: [games.baseGame],
    references: [games.id],
    relationName: "baseGame",
  }),
  suggestedPlayerCount: many(games_suggested_player_count, {
    relationName: "suggestedPlayerCount",
  }),
  _rels: many(games_rels, {
    relationName: "_rels",
  }),
}));
export const relations_libraries_rels = relations(
  libraries_rels,
  ({ one }) => ({
    parent: one(libraries, {
      fields: [libraries_rels.parent],
      references: [libraries.id],
      relationName: "_rels",
    }),
    gamesID: one(games, {
      fields: [libraries_rels.gamesID],
      references: [games.id],
      relationName: "games",
    }),
  })
);
export const relations_libraries = relations(libraries, ({ one, many }) => ({
  createdBy: one(users, {
    fields: [libraries.createdBy],
    references: [users.id],
    relationName: "createdBy",
  }),
  _rels: many(libraries_rels, {
    relationName: "_rels",
  }),
}));
export const relations_mechanics = relations(mechanics, () => ({}));
export const relations_media = relations(media, () => ({}));
export const relations_notes = relations(notes, ({ one }) => ({
  user: one(users, {
    fields: [notes.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_publishers_rels = relations(
  publishers_rels,
  ({ one }) => ({
    parent: one(publishers, {
      fields: [publishers_rels.parent],
      references: [publishers.id],
      relationName: "_rels",
    }),
    mediaID: one(media, {
      fields: [publishers_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
  })
);
export const relations_publishers = relations(publishers, ({ many }) => ({
  _rels: many(publishers_rels, {
    relationName: "_rels",
  }),
}));
export const relations_types = relations(types, () => ({}));
export const relations_usermedia = relations(usermedia, () => ({}));
export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: "roles",
  }),
}));
export const relations_users_rels = relations(users_rels, ({ one }) => ({
  parent: one(users, {
    fields: [users_rels.parent],
    references: [users.id],
    relationName: "_rels",
  }),
  librariesID: one(libraries, {
    fields: [users_rels.librariesID],
    references: [libraries.id],
    relationName: "libraries",
  }),
  gamenightsID: one(gamenights, {
    fields: [users_rels.gamenightsID],
    references: [gamenights.id],
    relationName: "gamenights",
  }),
  usersID: one(users, {
    fields: [users_rels.usersID],
    references: [users.id],
    relationName: "users",
  }),
  notesID: one(notes, {
    fields: [users_rels.notesID],
    references: [notes.id],
    relationName: "notes",
  }),
}));
export const relations_users = relations(users, ({ one, many }) => ({
  roles: many(users_roles, {
    relationName: "roles",
  }),
  avatar: one(usermedia, {
    fields: [users.avatar],
    references: [usermedia.id],
    relationName: "avatar",
  }),
  _rels: many(users_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    accessoriesID: one(accessories, {
      fields: [payload_locked_documents_rels.accessoriesID],
      references: [accessories.id],
      relationName: "accessories",
    }),
    artistsID: one(artists, {
      fields: [payload_locked_documents_rels.artistsID],
      references: [artists.id],
      relationName: "artists",
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: "categories",
    }),
    designersID: one(designers, {
      fields: [payload_locked_documents_rels.designersID],
      references: [designers.id],
      relationName: "designers",
    }),
    gamenightsID: one(gamenights, {
      fields: [payload_locked_documents_rels.gamenightsID],
      references: [gamenights.id],
      relationName: "gamenights",
    }),
    gamesID: one(games, {
      fields: [payload_locked_documents_rels.gamesID],
      references: [games.id],
      relationName: "games",
    }),
    librariesID: one(libraries, {
      fields: [payload_locked_documents_rels.librariesID],
      references: [libraries.id],
      relationName: "libraries",
    }),
    mechanicsID: one(mechanics, {
      fields: [payload_locked_documents_rels.mechanicsID],
      references: [mechanics.id],
      relationName: "mechanics",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    notesID: one(notes, {
      fields: [payload_locked_documents_rels.notesID],
      references: [notes.id],
      relationName: "notes",
    }),
    publishersID: one(publishers, {
      fields: [payload_locked_documents_rels.publishersID],
      references: [publishers.id],
      relationName: "publishers",
    }),
    typesID: one(types, {
      fields: [payload_locked_documents_rels.typesID],
      references: [types.id],
      relationName: "types",
    }),
    usermediaID: one(usermedia, {
      fields: [payload_locked_documents_rels.usermediaID],
      references: [usermedia.id],
      relationName: "usermedia",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  })
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  })
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  })
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  })
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({})
);

type DatabaseSchema = {
  enum_games_language_dependence: typeof enum_games_language_dependence;
  enum_users_roles: typeof enum_users_roles;
  accessories_alternate_names: typeof accessories_alternate_names;
  accessories: typeof accessories;
  accessories_rels: typeof accessories_rels;
  artists: typeof artists;
  categories: typeof categories;
  designers: typeof designers;
  gamenights: typeof gamenights;
  gamenights_rels: typeof gamenights_rels;
  games_suggested_player_count: typeof games_suggested_player_count;
  games: typeof games;
  games_rels: typeof games_rels;
  libraries: typeof libraries;
  libraries_rels: typeof libraries_rels;
  mechanics: typeof mechanics;
  media: typeof media;
  notes: typeof notes;
  publishers: typeof publishers;
  publishers_rels: typeof publishers_rels;
  types: typeof types;
  usermedia: typeof usermedia;
  users_roles: typeof users_roles;
  users: typeof users;
  users_rels: typeof users_rels;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_accessories_alternate_names: typeof relations_accessories_alternate_names;
  relations_accessories_rels: typeof relations_accessories_rels;
  relations_accessories: typeof relations_accessories;
  relations_artists: typeof relations_artists;
  relations_categories: typeof relations_categories;
  relations_designers: typeof relations_designers;
  relations_gamenights_rels: typeof relations_gamenights_rels;
  relations_gamenights: typeof relations_gamenights;
  relations_games_suggested_player_count: typeof relations_games_suggested_player_count;
  relations_games_rels: typeof relations_games_rels;
  relations_games: typeof relations_games;
  relations_libraries_rels: typeof relations_libraries_rels;
  relations_libraries: typeof relations_libraries;
  relations_mechanics: typeof relations_mechanics;
  relations_media: typeof relations_media;
  relations_notes: typeof relations_notes;
  relations_publishers_rels: typeof relations_publishers_rels;
  relations_publishers: typeof relations_publishers;
  relations_types: typeof relations_types;
  relations_usermedia: typeof relations_usermedia;
  relations_users_roles: typeof relations_users_roles;
  relations_users_rels: typeof relations_users_rels;
  relations_users: typeof relations_users;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres/types" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
